/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    stats: Stat;
    values: Value;
    'value-quotes': ValueQuote;
    quizzes: Quiz;
    'quiz-stages': QuizStage;
    'quiz-questions': QuizQuestion;
    'lead-submissions': LeadSubmission;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    values: ValuesSelect<false> | ValuesSelect<true>;
    'value-quotes': ValueQuotesSelect<false> | ValueQuotesSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    'quiz-stages': QuizStagesSelect<false> | QuizStagesSelect<true>;
    'quiz-questions': QuizQuestionsSelect<false> | QuizQuestionsSelect<true>;
    'lead-submissions': LeadSubmissionsSelect<false> | LeadSubmissionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required — SEO + accessibility.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * The one-liner.
   */
  blurb: string;
  status: 'live' | 'funded' | 'paying' | 'deeptech' | 'in-dev' | 'parked' | 'hidden';
  badge?: string | null;
  /**
   * The product’s own site.
   */
  outboundURL?: string | null;
  previewImage?: (number | null) | Media;
  order?: number | null;
  /**
   * Uncheck to keep off the site (e.g. Sales Agency).
   */
  showOnSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * e.g. "50 ms", "94%"
   */
  value: string;
  /**
   * One line.
   */
  label: string;
  /**
   * Popular name — Google / Forbes / Stanford.
   */
  source: string;
  /**
   * Fuller citation (footnote only).
   */
  sourceNote?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values".
 */
export interface Value {
  id: number;
  title: string;
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-quotes".
 */
export interface ValueQuote {
  id: number;
  quote: string;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  name: string;
  type: 'short' | 'long';
  entryHeading?: string | null;
  /**
   * Entry framing; the direct-contact hatch renders alongside.
   */
  entryCopy?: string | null;
  closeHeading?: string | null;
  closeCopy?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long quiz only — themed stages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-stages".
 */
export interface QuizStage {
  id: number;
  quiz: number | Quiz;
  title: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions".
 */
export interface QuizQuestion {
  id: number;
  quiz: number | Quiz;
  /**
   * Long quiz only.
   */
  stage?: (number | null) | QuizStage;
  order?: number | null;
  type: 'image' | 'tap';
  prompt: string;
  helperText?: string | null;
  options: {
    label: string;
    value: string;
    /**
     * For image-tile questions.
     */
    image?: (number | null) | Media;
    /**
     * e.g. "costFirst" flags a deal-breaker.
     */
    signalValue?: string | null;
    id?: string | null;
  }[];
  signalKey?:
    | ('none' | 'companySize' | 'context' | 'budget' | 'timeline' | 'dealBreaker' | 'taste' | 'feeling' | 'aspiration')
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-submissions".
 */
export interface LeadSubmission {
  id: number;
  kind: 'shortQuiz' | 'longQuiz' | 'contact';
  /**
   * [{ questionId, prompt, optionLabel, optionValue, signalKey, signalValue }]
   */
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * { name, email, company, note } as captured.
   */
  contact?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'reviewing' | 'prospect' | 'client' | 'declined') | null;
  dealBreakerFlag?: boolean | null;
  /**
   * { companySize, context, aspiration } pulled from signals.
   */
  derived?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal only.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'values';
        value: number | Value;
      } | null)
    | ({
        relationTo: 'value-quotes';
        value: number | ValueQuote;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'quiz-stages';
        value: number | QuizStage;
      } | null)
    | ({
        relationTo: 'quiz-questions';
        value: number | QuizQuestion;
      } | null)
    | ({
        relationTo: 'lead-submissions';
        value: number | LeadSubmission;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  blurb?: T;
  status?: T;
  badge?: T;
  outboundURL?: T;
  previewImage?: T;
  order?: T;
  showOnSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  source?: T;
  sourceNote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values_select".
 */
export interface ValuesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-quotes_select".
 */
export interface ValueQuotesSelect<T extends boolean = true> {
  quote?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  entryHeading?: T;
  entryCopy?: T;
  closeHeading?: T;
  closeCopy?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-stages_select".
 */
export interface QuizStagesSelect<T extends boolean = true> {
  quiz?: T;
  title?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions_select".
 */
export interface QuizQuestionsSelect<T extends boolean = true> {
  quiz?: T;
  stage?: T;
  order?: T;
  type?: T;
  prompt?: T;
  helperText?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        image?: T;
        signalValue?: T;
        id?: T;
      };
  signalKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-submissions_select".
 */
export interface LeadSubmissionsSelect<T extends boolean = true> {
  kind?: T;
  answers?: T;
  contact?: T;
  status?: T;
  dealBreakerFlag?: T;
  derived?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    beliefLine?: string | null;
    navLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSEO?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  organizationJSONLD?: {
    legalName?: string | null;
    url?: string | null;
    logo?: (number | null) | Media;
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The "in a hurry, talk to us directly" hatch.
   */
  contactChannels?: {
    email?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    /**
     * LOCKED belief line.
     */
    beliefLine?: string | null;
    subline?: string | null;
    /**
     * The scroll-reveal journey — text changes in place.
     */
    scrollBeats?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  problem?: {
    /**
     * One paragraph per row — revealed as they scroll.
     */
    narrative?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whatWeBuild?: {
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  labsIntro?: {
    /**
     * The stated belief transition in.
     */
    beliefBeat?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  creatorMention?: {
    body?: string | null;
    href?: string | null;
  };
  cta?: {
    heading?: string | null;
    body?: string | null;
    quizLabel?: string | null;
    hatchLabel?: string | null;
  };
  about?: {
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The "small senior team, top-0.5% bar" line — present, not headlined.
     */
    teamLine?: string | null;
    contactHeading?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        beliefLine?: T;
        navLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        copyright?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSEO?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  organizationJSONLD?:
    | T
    | {
        legalName?: T;
        url?: T;
        logo?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  contactChannels?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        beliefLine?: T;
        subline?: T;
        scrollBeats?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        narrative?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  whatWeBuild?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  labsIntro?:
    | T
    | {
        beliefBeat?: T;
        heading?: T;
        body?: T;
      };
  creatorMention?:
    | T
    | {
        body?: T;
        href?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        body?: T;
        quizLabel?: T;
        hatchLabel?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        teamLine?: T;
        contactHeading?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}